---
driver_plugin: vagrant
provisioner: chef_zero

platforms:
- name: centos-6.4_chef-11.4.4
  driver_config:
    box: opscode-centos-6.4_chef-11.4.4
    box_url:  https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
- name: ubuntu-12.04_chef-11.4.4
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box

suites:
- name: default
  run_list:
    - recipe[etcd]
    - recipe[ktc-database]
    - recipe[ktc-memcached]
    - recipe[ktc-messaging]
    - recipe[ktc-identity]
    - recipe[ktc-image]
    - recipe[ktc-metering]
  attributes:
    ha_disabled: true
    mysql:
      allow_remote_root: true
      root_network_acl: '%'
    openstack:
      developer_mode: true

clusters:
  default:
    - default
